site_name: BigC
site_description: BigC Documentation
site_url: https://gobigc.github.io/wiki/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Start here: 0-housekeeping/index.md
  - Grammar & Source code samples: 1-grammar/index.md
  - Semantic Analysis: 2-syntaxAnalyzer/index.md
  - Syntax Analysis: 3-semanticAnalyzer/index.md
  - Code Generation: 4-codeGenerator/index.md
  - FAQ: faq.md
  - Contributing: contributing.md