site_name: BigC
site_description: BigC Documentation
site_url: https://gobigc.github.io/wiki/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

nav:
  - About BigC:
    - index.md
    - Home: 
      - Design Choices: 0-housekeeping/designChoices.md
      - Tech Stack: 0-housekeeping/techStack.md
    - Grammar:
      - Bible: 1-grammar/bible.md
      - Proof: 1-grammar/proof.md
      - Sample: 1-grammar/sample.md
    - Syntax Analyzer:
      - Interface: 2-syntaxAnalyzer/interface.md
    - Semantic Analyzer:
      - Interface: 3-semanticAnalyzer/interface.md
    - Code Generator:
      - Interface: 4-codeGenerator/interface.md
    - Contributing: contributing.md
    - FAQ: faq.md